"use client";

import { useEffect, useState } from "react";
import { Transaction } from "@mysten/sui/transactions";
import { useSuiClient } from "@mysten/dapp-kit";
import { useEnokiFlow, useZkLogin } from "@mysten/enoki/react";
import { getFaucetHost, requestSuiFromFaucetV0 } from "@mysten/sui/faucet";
import { ExternalLink, Github, LoaderCircle, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { toast } from "sonner";
import { BalanceChange } from "@mysten/sui/client";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { track } from "@vercel/analytics";
import { useCustomWallet } from "@/contexts/CustomWallet";
import { USER_ROLES } from "@/constants/USER_ROLES";

export default function Page() {

  const { isConnected, logout, redirectToAuthUrl, emailAddress, address } = useCustomWallet();

  if (isConnected) {
    return (
      <div>
        <h1 className="text-4xl font-bold m-4">Enoki Demo App</h1>
        <Popover>
          <PopoverTrigger className="absolute top-4 right-4 max-w-sm" asChild>
            <div>
              <Button className="hidden sm:block" variant={"secondary"}>
                {emailAddress}
              </Button>
              <Avatar className="block sm:hidden">
                <AvatarImage src="https://github.com/shadcn.png" />
                <AvatarFallback>CN</AvatarFallback>
              </Avatar>
            </div>
          </PopoverTrigger>
          <PopoverContent>
            <Card className="border-none shadow-none">
              {/* <Button variant={'ghost'} size='icon' className="relative top-0 right-0" onClick={getAccountInfo}><RefreshCw width={16} /></Button> */}
              <CardHeader>
                <CardTitle>Account Info</CardTitle>
                <CardDescription>
                  View the account generated by Enoki&apos;s zkLogin flow.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <>
                  <div className="flex flex-row gap-1 items-center">
                    <span>Address: </span>
                      <div className="flex flex-row gap-1">
                        <span>{`${address?.slice(
                          0,
                          5
                        )}...${address?.slice(63)}`}</span>
                        <a
                          href={`https://suiscan.xyz/testnet/account/${address}`}
                          target="_blank"
                        >
                          <ExternalLink width={12} />
                        </a>
                      </div>
                  </div>
                </>
              </CardContent>
              <CardFooter className="flex flex-row gap-2 items-center justify-between">
                <Button
                  variant={"destructive"}
                  size={"sm"}
                  className="w-full text-center"
                  onClick={logout}
                >
                  Logout
                </Button>
              </CardFooter>
            </Card>
          </PopoverContent>
        </Popover>
        <div className="flex flex-col items-center sm:flex-row gap-4 sm:items-start">
          
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-col items-center justify-start">
      <a
        href="https://github.com/dantheman8300/enoki-example-app"
        target="_blank"
        className="absolute top-4 right-0 sm:right-4"
        onClick={() => {
          track("github");
        }}
      >
        <Button variant={"link"} size={"icon"}>
          <Github />
        </Button>
      </a>
      <div>
        <h1 className="text-4xl font-bold m-4">Enoki Demo App</h1>
        <p className="text-md m-4 opacity-50 max-w-md">
          This is a demo app that showcases the{" "}
          <a
            href="https://portal.enoki.mystenlabs.com"
            target="_blank"
            className="underline cursor-pointer text-blue-700 hover:text-blue-500"
          >
            Enoki
          </a>{" "}
          zkLogin flow and sponsored transaction flow. NOTE: This example runs
          on the <span className="text-blue-700">Sui test network</span>
        </p>
      </div>
      <Button onClick={() => {redirectToAuthUrl(USER_ROLES.ROLE_2)}}>Sign in with Google</Button>
      <Button className="bg-[#0C0F1D] rounded-xl border border-[#99EFE4] transform hover:scale-110 transition-transform hover:bg-[#99EFE4] bg-[#99EFE4] text-[#0C0F1D]" onClick={() => {
        console.log("Sponsorship in the front-end...");
        redirectToAuthUrl(USER_ROLES.ROLE_2);
      }}>
          Log in to vote
        </Button>
    </div>
  );
}
